version: 1

services:
  - type: web
    name: altona-village-backend
    env: python
    buildCommand: pip install -r requirements.txt || pip install -r altona_village_cms/requirements.txt
    startCommand: gunicorn "altona_village_cms.src.main:app" --workers=2 --timeout=120 -b 0.0.0.0:$PORT
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: JWT_SECRET_KEY
        generateValue: true
      - key: CORS_ORIGINS
        value: https://altona-village-frontend.onrender.com,http://localhost:5173
    autoDeploy: true

staticSites:
  - name: altona-village-frontend
    rootDir: altona-village-frontend
    buildCommand: npm ci && npm run build
    publishPath: dist
    envVars:
      - key: VITE_API_BASE
        value: https://altona-village-backend.onrender.com/api
